# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      #- name: instal JSDOM
      #  run: npm install jsdom

      #- name: Generate README.md
      #  run: |
      #    node -e "
      #    const fs = require('fs');
      #    const { JSDOM } = require('jsdom');
          
      #    // Load index.html
      #    const htmlContent = fs.readFileSync('docs/index.html', 'utf-8');
      #    const dom = new JSDOM(htmlContent);
          
      #    // Extract <title> and first <p> as description
      #    const title = dom.window.document.querySelector('title')?.textContent || 'My Project';
      #    const description = dom.window.document.querySelector('p')?.textContent || 'Description not available.';
          
      #    // Generate README content
      #    const readmeContent = \`# \${title}\n\n\${description}\n\nThis README was generated automatically from docs/index.html.\`;
          
      #    // Write to README.md
      #    fs.writeFileSync('README.md', readmeContent);
      #    "

      - name: Update Title
        run: |
          # Read the new title from input
          NEW_TITLE="${{ github.event.inputs.title }}"

          # Use sed to update the title in index.html
          sed -i.bak "s|<title>.*</title>|<title>$NEW_TITLE</title>|" docs/index.html

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test 

      - name: Commit and push README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html docs/index.html.bak
          git commit -m "Update Title"
          git push
