# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      name: Generate README.md
        run: |
          # Read the contents of index.html
          CONTENT=$(cat index.html)

          # Create the README.md content
          echo "# $TITLE" > README.md
          echo "" >> README.md
          echo "$DESCRIPTION" >> README.md
          echo "" >> README.md
          echo "## Features" >> README.md
          echo "$FEATURES" >> README.md

      - name: Commit and push README.md
        run: |
          git config --local dianaabreulopes1996@gmail.com "action@github.com"
          git config --local DianaLopesA "GitHub Action"
          git add README.md
          git commit -m "Update README.md from index.html"
          git push
